config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'static_pages#about'
  get 'sessions/new'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'sign_up' => 'users#new'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # You can have the root of your site routed with "root"
  resources :users
  root 'sessions#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	has_secure_password
	validates :login, :presence => true, uniqueness: true
	validates :password, :confirmation => true, :presence => true
	validates :password_confirmation, :presence => true

	  # Возвращает дайджест данной строки
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Возвращает случайный токен
    def User.new_token
       SecureRandom.urlsafe_base64
    end

    def remember
       self.remember_token = User.new_token
       update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Возвращает true, если предоставленный токен совпадает с дайджестом.
    def authenticated?(remember_token)
       return false if remember_digest.nil?
       BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Забывает пользователя
    def forget
      update_attribute(:remember_digest, nil)
    end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
		log_in user
		puts params[:session][:remember_me]
		params[:session][:remember_me] == '1' ? remember(user) : forget(user)
		redirect_to user
      # Осуществить вход пользователя и перенаправление на страницу профиля.
    else
      # Выдать сообщение об ошибке.
      flash.now[:danger] = 'Invalid email/password combination' # Не совсем верно!
      render 'new'
    end
  end

  def destroy
  	log_out if is_logged_in
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/user_info_controller.rb
class UserInfoController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  	@user = User.find(params[:id])
    @userInfo = UserInfo.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @userInfo = UserInfo.create(:id => @user.id)
        format.html { redirect_to @user}
        format.json { render :show, status: :created, location: @user }
        log_in @user

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :login, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

    # Запоминает пользователя в постоянную сессию.
    def remember(user)
       user.remember
       cookies.permanent.signed[:user_id] = user.id
       cookies.permanent[:remember_token] = user.remember_token
    end

	def current_user
	  if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
	end

	# Возвращает true, если пользователь вошел, иначе false.
	def is_logged_in
		!current_user.nil?
	end

	# Осуществляет выход текущего пользователя.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

  # Забывает постоянную сессии.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_info_helper.rb
module UserInfoHelper
end

app/helpers/users_helper.rb
module UsersHelper
  attr_accessor :name
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:style="http://www.w3.org/1999/xhtml">
  <head>
    <title></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application.js'%>
  </head>
  <body>
	<nav class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigator">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Будь добрее", '#', id: "homeLink" %>
        <%= link_to "Что это?", {:controller => 'static_pages', :action => 'about'} %>
      </div>
      <div class="collapse navbar-collapse" id="navigator">
        <ul class="nav navbar-nav navbar-right">
          <% if is_logged_in %>
            <li><%= link_to "Профиль", current_user %></li>
            <li><%= link_to "Выйти", logout_path %></li>
          <% else %>
            <li><%= link_to "Войти", login_path %></li>
          <% end %>
          <li><%= link_to "Помощь",   '#' %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div style="margin-top: 75px">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
   <!-- <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>-->
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="container" style="width: 80%">
  <ul>
    <li class="thumbnail" style='background-color: rgba(128,0,128,0.3); border: transparent;'>
        <p class="about_page_header">Эти странные люди...</p>
        <p class="about_page_text">
          Иногда люди поступают довольно странно: случайно обраненное слово становится огнивом в соломенном доме,
          безобидная фраза вызывает неугомонную агрессию. Вчерашние друзья становятся врагами из-за простой шутки.
        </p>
    </li>
    <li class="thumbnail" style='background-color: rgba(128,0,128,0.3); border: transparent;'>
      <p class="about_page_header">И такие же странные действия...</p>
      <p class="about_page_text">
        Казалось бы в чем проблема: просто ненавидь человека и всё.
        Но потом будут случайные встречи. Возможно, человек, на которого ты обозлился, потом устроится на работу
        в твой офис. Вдруг этот человек окажется знакомым или родственником того, кто тебе нравится.
        Так много возможностей, и все они приводят к твоей неловкости, когда, например, ты приходишь на ужин к своей девушке,
        а ее отец - водитель автобуса, с которым ты поругался вчера из-за сдачи.
      </p>
    </li>
    <li class="thumbnail" style='background-color: rgba(128,0,128,0.3); border: transparent;'>
      <p class="about_page_header">Можно сделать иначе...</p>
      <p class="about_page_text">
        Что если попытаться отучить человека от черствости, от грубости? Простыми шагами прийти к ситуации, когда даже в мыслях
        не будет мата.
      </p>
    </li>
  </ul>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div id = "loginWindow">
	<%= render 'shared/error_messages', style: 'position: absolute' %>
  <div class="row row-margin-0">
		<%= form_for(@user) do |f| %>
        <div class="col-lg-3 text-left" style="margin-top: 25px;">
					<%= f.label :login %>
        </div>
        <div class="col-lg-9" style="margin-top: 25px;">
					<%= f.text_field(:login, class: 'field')%>
					<% if @user.errors.messages.include?(:login) %>				  
					    <%= @user.errors.messages[:login].first %>
					<% end %>
        </div>
        <div class="col-lg-3 text-left" style="margin-top: 25px;">
					<%= f.label :email %>	
        </div>
        <div class="col-lg-9" style="margin-top: 25px;">
					<%= f.email_field(:email, class: 'field') %>
					<% if @user.errors.messages.include?(:email) %>				  
					    <%= @user.errors.messages[:email].first %>
          <% end %>
        </div>
        <div class="col-lg-3 text-left" style="margin-top: 25px;">
					<%= f.label :password %>
        </div>
        <div class="col-lg-9" style="margin-top: 25px;">
					<%= f.password_field(:password, class: 'field')%>
					<% if @user.errors.messages.include?(:password) %>				  
					  <%= @user.errors.messages[:password].first %>
				  <% end %>
			  </div>
        <div class="col-lg-3 text-left" style="margin-top: 25px;">
					<%= f.label :password_confirmation, "Confirmation" %>
        </div>
        <div class="col-lg-9" style="margin-top: 25px;">
					<%= f.password_field(:password_confirmation, class: 'field')%>
					<% if @user.errors.messages.include?(:password_confirmation) %>				  
					    <%= @user.errors.messages[:password_confirmation].first %>
				    <% end %>
        </div>
        <div class="col-lg-12" style="margin-top: 25px;">
         <%= f.submit "Create account", class: "btn btn-primary btn-block btn-square" %>
       </div>
      </div>
		<% end %>	
</div>

app/views/users/show.html.erb
<%= javascript_include_tag 'application.js'%>
<div class="container" style="width: 800px">
  <div class="row" style="height: 150px;">
    <img src="<%=image_path'Qk0P5PLItD8.jpg' %>" id="user_top_image">
  </div>
  <div class="row" style="margin-top: -100px;">
    <div class="thumbnail">
      <div class="col-lg-4 col-sm-4 col-md-2 col-xs-12 image-container">
        <img src="<%=image_path'lighter.gif' %>" class='img-circle pull-lg-left' id="user_big_avatar">
      </div>
    </div>
  </div>
  <div class="row" style="background-color: white; margin-top: -100px;  border: 2px solid gray;">
    <div class="col-sm-8 col-sm-offset-4" style="margin-top: -95px">
        <p class="user_name"><%=@userInfo.first_name %> <%=@userInfo.last_name %></p>
        <p class="user_name"><%=@userInfo.name %></p>
        <p class="user_message_world"><%=@userInfo.message_world %></p>
    </div>
  </div>
  <div class="row" style="border: 2px solid gray; border-top: 0px">
    <ul class="nav nav-tabs" style="background-color: rgb(220,220,220)">
      <li class="active">
        <a href="#">Личная информация</a>
      </li>
      <li><a href="#">Стена</a></li>
      <li><a href="#">Лента</a></li>
    </ul>
  </div>
  <div class="row" style="border: 2px solid gray; border-top: 0px;background-color: white">
    <div class="col-sm-3" style="border-right: 2px solid lightgray">
      Друзья
    </div>
    <div class="col-sm-9">ГОВНО</div>
  </div>
</div>